spring:
  application:
    name: qiyu-live-msg-provider
  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
    driver-class-name: com.mysql.cj.jdbc.Driver
    #访问主库
    url: jdbc:mysql://cloud.db:8808/qiyu_live_msg?useUnicode=true&characterEncoding=utf8
    username: root
    password: qiyu@123
  data:
    redis:
      port: 8801
      host: cloud.db
      password: qiyu@9810
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

qiyu:
  rmq:
   consumer:
     nameSrv: qiyu.rmq.com:9876
     groupName: qiyuLiveMqApplication
   producer:
     nameSrv: qiyu.rmq.com:9876
     groupName: ${spring.application.name}
     applicationName: ${spring.application.name}
     sendMsgTimeout: 3000
     retryTimes: 2
  sms:
    ccp: 
     smsServerIp: app.cloopen.com
     port: 8883
     accountSId: 2c94811c88bf35030188c75f3378028b
     accountToken: e5863b87904e4be0bec592d6e4006f84
     appId: 2c94811c88bf35030188c75f34c60292
     templateId: 1
     testPhone: 13510647925 

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://qiyu.nacos.com:8848?namespace=qiyu-live-test&&username=qiyu_rw&&password=qiyu1867122
  protocol:
    name: dubbo
    port: 9092